name: Bug report
description: Report a reproducible problem in Glean.
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this issue.
        Please include enough detail for us to reproduce quickly.

  - type: input
    id: version
    attributes:
      label: Glean version
      description: Output of `glean --version` if available.
      placeholder: "v0.1.0"
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, shell, and installation method.
      placeholder: |
        macOS 14 / zsh
        Installed via bun link
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Provide exact commands and/or clipboard workflow steps.
      placeholder: |
        1. Copy HTML from Chrome DevTools
        2. Run `glean --tui`
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
      description: Paste relevant output or attach screenshots.
      render: shell
    validations:
      required: false
